# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\";\n\x07Message\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"4\n\x12SendMessageRequest\x12\x1e\n\x07message\x18\x01 \x01(\x0b\x32\r.chat.Message\"\x07\n\x05\x45mpty\"\x1e\n\x0e\x43onnectRequest\x12\x0c\n\x04user\x18\x01 \x01(\t2}\n\x0b\x43hatService\x12\x38\n\x0fReceiveMessages\x12\x14.chat.ConnectRequest\x1a\r.chat.Message0\x01\x12\x34\n\x0bSendMessage\x12\x18.chat.SendMessageRequest\x1a\x0b.chat.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=20
  _globals['_MESSAGE']._serialized_end=79
  _globals['_SENDMESSAGEREQUEST']._serialized_start=81
  _globals['_SENDMESSAGEREQUEST']._serialized_end=133
  _globals['_EMPTY']._serialized_start=135
  _globals['_EMPTY']._serialized_end=142
  _globals['_CONNECTREQUEST']._serialized_start=144
  _globals['_CONNECTREQUEST']._serialized_end=174
  _globals['_CHATSERVICE']._serialized_start=176
  _globals['_CHATSERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
